DROP EXTENSION IF EXISTS postgis CASCADE;
DROP EXTENSION IF EXISTS pgcrypto CASCADE;

DROP TABLE IF EXISTS MapPoint CASCADE;

CREATE EXTENSION postgis;
CREATE EXTENSION postgis_topology;
CREATE EXTENSION pgcrypto;

CREATE TABLE MapPoint(
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(100) NOT NULL,
    url VARCHAR(100) NOT NULL,
    start_date DATE NOT NULL,
    geom GEOMETRY NOT NULL
);

CREATE TABLE DiseasePoint() INHERITS(MapPoint);
CREATE TABLE PestPoint() INHERITS(MapPoint)