DROP EXTENSION IF EXISTS postgis CASCADE;
DROP EXTENSION IF EXISTS pgcrypto CASCADE;

DROP TABLE IF EXISTS MapPoint CASCADE;

CREATE EXTENSION postgis;
CREATE EXTENSION postgis_topology;
CREATE EXTENSION pgcrypto;

CREATE TABLE MapPoint(
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(100) NOT NULL,
    url VARCHAR(100) NOT NULL,
    start_date DATE NOT NULL DEFAULT NOW(),
    point GEOMETRY(Point, 4326) NOT NULL,
    radius INTEGER NOT NULL
);

CREATE TABLE DiseasePoint() INHERITS(MapPoint);
CREATE TABLE PestPoint() INHERITS(MapPoint);

GRANT USAGE ON SCHEMA public to croper; 
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO croper;
GRANT SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO croper;
GRANT SELECT, UPDATE, INSERT, DELETE ON ALL TABLES IN SCHEMA public TO croper;